bookers2/config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get '/home/about' => 'homes#about'
  devise_for :users
  resources :books, only: [:show, :edit, :index, :destroy, :create, :update]
  resources :users, only: [:show, :index, :update]
  get 'users/:id/edit' => 'users#edit', as: 'edit_user'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
 

bookers2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
  #has_one_attached :image
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true,  length: {  maximum: 200 }
end

bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   has_many :books, dependent: :destroy


  has_one_attached :profile_image

  def get_profile_image(h, w)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [h, w]).processed
  end



 validates :name,
    length: { minimum: 2, maximum: 20 },
    uniqueness: true
  
   validates :introduction,
    length: { maximum: 50 } 
    
    
    
    
end

bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, except: [:top, :about]
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

   private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
    end

    def after_sign_in_path_for(resource)
      user_path (current_user)
    end

    

end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController




  def index
    @book = Book.new
    @books  = Book.all
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @books  = Book.all
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to '/books'
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  def create
    @book = Book.new(book_params)
    @book.user_id=current_user.id
      if @book.save
        flash[:notice] = "Your book was successfully created."
        redirect_to book_path(@book.id)
      else
         @user = current_user
         @books = Book.all
        render :index
      end
  end


  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
        flash[:notice] = "Your book was successfully updated."
         redirect_to book_path(@book.id)
    else
        render :edit
    end
  end


    private
  def book_params
    params.require(:book).permit(:title, :body, :image)
  end


end

bookers2/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
    
end

bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
   @user = User.find(params[:id])
    if @user == current_user
     render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def index
   @user = current_user
   @users = User.all
  end

  def update
     @user = User.find(params[:id])
     if @user.update(user_params)
       flash[:notice] = "Your profile was successfully updated."
       redirect_to  user_path(@user.id)
     else
      render :edit
     end
  end

private
def user_params
  params.require(:user).permit(:name, :introduction, :profile_image)
end

# def correct_user
#     @user = User.find(params[:id])
#     @book = @user.books
#     redirect_to(user_path) unless @book == current_user
# end

end

bookers2/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2/app/helpers/users_helper.rb
module UsersHelper
end

bookers2/app/views/books/_user_info.html.erb
  <div class="col-md-3">
        <h2>User info</h2>

         <%= image_tag current_user.get_profile_image(100,100) %>
        <table class="table">
         <tbody>
           <tr></tr>
           <tr>
  	         <th>Name
  	         </th>
  	         <th><%= user.name %></th>
           </tr>
          <tr>
        	  <th>introduction</th>
        	  <th> <%= user.introduction %></th>
          </tr>
         </tbody>
        </table>
        <div class="row">

        <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
        </div>

        <h2 class="mt-3">New book</h2>
         <%= form_with model: Book.new do |f| %>
        <div class="form-group">
          Title
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
        <div class="form-group">
          Opinion
          <%= f.text_area :body, class:"form-control book_body"  %>
        </div>
        <div class="form-group">
           <%= f.submit "Create Book", class:"btn btn-success" %>
       </div>
         <% end %>
   </div>

bookers2/app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors occurred
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>

         <%= form_with model: @book,method: :patch  do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title,class:"form-control book_title" %>
        </div>

        <div class="form-group">
          <label for="book_body">Opinion</label>
          <%= f.text_area :body,class:"form-control book_body" %>
        </div>

        <div class="form-group">
      	  <%= f.submit "Update Book",class:"btn btn-success"  %>
        </div>
        	<%= link_to "Show", book_path(@book.id) %> |
      	<%= link_to "Back", books_path %>
        	<% end %>
    </div>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors occurred
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container px-5 px-sm-0">
 <div class="row">
    <%= render 'books/user_info', user:@user %>

    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
           <% @books.each do |book| %>
         <tr>
           <td>
              <%= link_to user_path(book.user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100)%>
              <% end %>
           </td>
            <td>
            <%= link_to book.title, book_path(book.id)%>
            </td>
             <td><%= book.body %></td>
          </tr>
           <% end %>
          </tbody>
     </table>
    </div>
 </div>
</div>

bookers2/app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <%= render 'user_info', user:@user %>

  <div class="col-md-8 offset-md-1">
  		<h2>Book detail</h2>
  		<table class="table">
  		  <tbody>
  		    <tr>
  		     <td>
   		      <%= image_tag @user.get_profile_image(100,100) %><br>
   		      <%= link_to @user.name, user_path(@user.id) %>
    		    </td>
          <td><%=link_to  @book.title, book_path(@book.id) %>
          </td>

          <td><%= @book.body %>
          </td>
          
          <% if @book.user == current_user %>
           <td>
            <%= link_to edit_book_path(@book.id), class:"btn btn-sm btn-success" do %>
               <i>Edit</i>
            <% end %>
           </td>
           <td>
             <%= link_to book_path(@book.id), method: :delete, class:"btn btn-sm btn-danger", "data-confirm" => "本当に消しますか?" do %>
              <i>Destroy</i>
              <% end %>
           </td>
          <% end %>
         </tr>
      </tbody>
      </table>
    </div>
  </div>
</div>

bookers2/app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i> <strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>

bookers2/app/views/homes/top.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>

bookers2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <header>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
           <%= link_to user_path(current_user), class:"nav-link text-light" do %>
            <i class="fas fa-home"></i>
            Home
           <% end %>
          </li>
          <li>
           <%= link_to users_path, class:"nav-link text-light" do %>
           <i class="fas fa-users"></i>
           Users
           <% end %>
          </li>
           <li>
           <%= link_to books_path, class:"nav-link text-light" do %>
           <i class="fas fa-book-open"></i>
           Books
           <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
            <i class="fas fa-sign-out-alt"></i>
            Log out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path, class:"nav-link text-light" do %>
            <i class="fas fa-home"></i>
            Home
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path, class:"nav-link text-light" do %>
            <i class="fas fa-link"></i>
            About
            <% end %>
          </li>
          <li>
           <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
           <i class="fas fa-user-plus"></i>
           Sign up
           <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path, class:"nav-link text-light" do%>
            <i class="fas fa-sign-in-alt"></i>
            Log in
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
     </header>
     <body>
       <div>
        <%= flash[:notice] %>
        <div>
        <%= yield %>
     </body>
     <footer>
      <div class="container mt-5">
      	<div class="row">
        	<div class="mx-auto">
        		<p>CopyRight Infratop.inc</p>
        	</div>
        </div>
      </div>
    </footer>
  </body>
</html>

bookers2/app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors occurred
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
      
  	<%= form_with model:@user,method: :patch do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
        	<%= f.text_field :name, autofocus: true, id:"user_name", placeholder:"名前",class:"form-control name"%>
        </div>
  
       <div class="form-group">
          <label for="user_image">Image</label>
  	      <%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*", class:"form-control-file user_image" %> 
        </div>
  
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
  	      <%= f.text_area :introduction, autofocus: true, id:"user_name",placeholder:"自己紹介文", class:"form-control introduction"%>
        </div>
        <div class="form-group">
  	     <%= f.submit "Update User",class:"btn btn-secondary" %>
    <% end %>
        </div> 
    </div>
  </div>
</div>

bookers2/app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <%= render 'books/user_info', user:@user %>

  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
         <% @users.each do |user| %>
        <tr>
          <td>
            <%= image_tag user.get_profile_image(80,80)%>
        	</td>
        	<td>
        	  <%= user.name %>
        	</td>

        	<td>
        	  <%= link_to 'Show', user_path(user.id)%>
    	    </td>
        		<% end %>
        </tr>
      </tbody>
    </table>
  </div>
 </div>
</div>

bookers2/app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <%= render 'books/user_info', user:@user %>


  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
        </thead>
      	<% @books.each do |book| %>
        <tbody>
          <tr>
          	<td>
          	 <%= link_to user_path(book.user.id) do %>
          	<%= image_tag book.user.get_profile_image(80,80) %>
          	 <% end %>
          	</td>
          	<td>
          	<%=link_to book.title, book_path(book.id) %>
          	</td> 
          	<td>
          	<%= book.body %>
          	</td>           
           </tr>
        </tbody>
      	<% end %>
    </table>
  </div>
 </div>
</div>